// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./hello_world')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '../parts/hello_world.vue'
import {isView} from 'vueonrails'
import TurbolinksAdapter from 'vue-turbolinks'
Vue.use(TurbolinksAdapter)

document.addEventListener('turbolinks:load', () => {
  if (isView('pages#index')) {
    document.body.appendChild(document.createElement('helloWorld'))
    const home = new Vue({
        render: h => h(App)
    }).$mount('helloWorld')
    console.log({home})
  }
})